import { $, $$ } from "../core/dom.js";
import type { Elements } from "./elements.js";

export function bindElements(): Elements {
  return {
    app: $(".app"),
    tabs: $$(".nav-item") as HTMLElement[],
    panels: $$(".tab-panel") as HTMLElement[],
    pageTitle: $("#pageTitle") as HTMLElement,
    sidebar: $("#sidebar") as HTMLElement,
    sidebarToggle: $("#sidebarToggle") as HTMLButtonElement | null,
    mobileNavToggle: $("#mobileNavToggle") as HTMLButtonElement | null,
    sidebarOverlay: $("#sidebarOverlay") as HTMLElement,
    sidebarStatusText: $("#sidebarStatusText") as HTMLElement,
    sidebarStatusDot: $("#sidebarStatusDot") as HTMLElement,
    topStatusPill: $("#topStatusPill") as HTMLElement,
    topLatency: $("#topLatency") as HTMLElement,
    topPer: $("#topPer") as HTMLElement,
    themeToggle: $("#themeToggle") as HTMLButtonElement,
    themeIconLight: $("#themeIconLight"),
    themeIconDark: $("#themeIconDark"),

    connectionMode: $("#connectionMode") as HTMLSelectElement,
    connectBtn: $("#connectBtn") as HTMLButtonElement,
    pingBtn: $("#pingBtn") as HTMLButtonElement,
    latencyTestBtn: $("#latencyTestBtn") as HTMLButtonElement | null,
    latencyWarning: $("#latencyWarning"),
    connectionStatusPill: $("#connectionStatusPill") as HTMLElement,
    latencyValue: $("#latencyValue") as HTMLElement,
    perValue: $("#perValue") as HTMLElement,
    healthMode: $("#healthMode"),

    logToggleBtn: $("#logToggleBtn") as HTMLButtonElement,
    sidebarLogBtn: $("#sidebarLogBtn") as HTMLButtonElement,
    sessionsLogBtn: $("#sessionsLogBtn") as HTMLButtonElement,
    loggingStatus: $("#loggingStatus") as HTMLElement,

    freqRange: $("#freqRange") as HTMLInputElement,
    freqNumber: $("#freqNumber") as HTMLInputElement,
    ampRange: $("#ampRange") as HTMLInputElement,
    ampNumber: $("#ampNumber") as HTMLInputElement,
    noiseRange: $("#noiseRange") as HTMLInputElement,
    noiseNumber: $("#noiseNumber") as HTMLInputElement,
    enableTremor: $("#enableTremor") as HTMLInputElement,
    sendBtn: $("#sendBtn") as HTMLButtonElement,
    stopBtn: $("#stopBtn") as HTMLButtonElement,
    lastSent: $("#lastSent") as HTMLElement,
    unsavedIndicator: $("#unsavedIndicator") as HTMLElement,

    freezeBtn: $("#freezeBtn") as HTMLButtonElement,
    clearBtn: $("#clearBtn") as HTMLButtonElement,
    tremorCanvas: $("#tremorCanvas") as HTMLCanvasElement,
    chartContainer: $("#chartContainer") as HTMLElement | null,
    chartTooltip: $("#chartTooltip") as HTMLElement | null,
    chartLive: $("#chartLive"),
    spectrumCanvas: $("#spectrumCanvas") as HTMLCanvasElement,
    sampleRateValue: $("#sampleRateValue"),
    spectrumFreezeBtn: $("#spectrumFreezeBtn") as HTMLButtonElement | null,
    windowRange: $("#windowRange") as HTMLInputElement | null,
    windowValue: $("#windowValue"),
    gainRange: $("#gainRange") as HTMLInputElement | null,
    gainValue: $("#gainValue"),
    snapshotBtn: $("#snapshotBtn") as HTMLButtonElement | null,

    metricFrequency: $("#metricFrequency") as HTMLElement,
    metricRMS: $("#metricRMS") as HTMLElement,
    metricPower: $("#metricPower") as HTMLElement,
    metricRegularity: $("#metricRegularity") as HTMLElement,
    metricUPDRS: $("#metricUPDRS") as HTMLElement,
    metricSNR: $("#metricSNR") as HTMLElement,
    metricPeakToPeak: $("#metricPeakToPeak") as HTMLElement,
    metricBandwidth: $("#metricBandwidth") as HTMLElement,
    metricStability: $("#metricStability") as HTMLElement,
    metricHarmonic: $("#metricHarmonic") as HTMLElement,

    freqIndicator: $("#freqIndicator") as HTMLElement,
    rmsIndicator: $("#rmsIndicator") as HTMLElement,
    powerIndicator: $("#powerIndicator") as HTMLElement,
    regularityIndicator: $("#regularityIndicator") as HTMLElement,
    updrsIndicator: $("#updrsIndicator") as HTMLElement,
    snrIndicator: $("#snrIndicator") as HTMLElement,
    peakToPeakIndicator: $("#peakToPeakIndicator") as HTMLElement,
    bandwidthIndicator: $("#bandwidthIndicator") as HTMLElement,
    stabilityIndicator: $("#stabilityIndicator") as HTMLElement,
    harmonicIndicator: $("#harmonicIndicator") as HTMLElement,

    profileSelect: $("#profileSelect") as HTMLSelectElement,
    loadProfileBtn: $("#loadProfileBtn") as HTMLButtonElement,
    saveProfileBtn: $("#saveProfileBtn") as HTMLButtonElement,
    profilesTable: $("#profilesTable tbody") as HTMLElement,
    profilesEmpty: $("#profilesEmpty") as HTMLElement,
    profileModal: $("#profileModal") as HTMLElement,
    profileForm: $("#profileForm") as HTMLFormElement,
    profileName: $("#profileName") as HTMLInputElement,

    sequenceList: $("#sequenceList") as HTMLElement,
    sequenceEditor: $("#sequenceEditor") as HTMLElement,
    sequencesEmpty: $("#sequencesEmpty") as HTMLElement,
    newSequenceBtn: $("#newSequenceBtn") as HTMLButtonElement,

    sessionsTable: $("#sessionsTable tbody") as HTMLElement,
    sessionsEmpty: $("#sessionsEmpty") as HTMLElement,
    sessionModal: $("#sessionModal") as HTMLElement,
    sessionSummary: $("#sessionSummary") as HTMLElement,
    sessionCanvas: $("#sessionCanvas") as HTMLCanvasElement,
    deleteSessionBtn: $("#deleteSessionBtn") as HTMLButtonElement,
    exportCsvBtn: $("#exportCsvBtn") as HTMLButtonElement,
    exportJsonBtn: $("#exportJsonBtn") as HTMLButtonElement,

    settingDarkMode: $("#settingDarkMode") as HTMLInputElement | null,
    settingHighContrast: $("#settingHighContrast") as HTMLInputElement | null
  };
}
